#!/usr/bin/env bats

# init tests focus on the manifest-writing path. init's final step is
# `exec sync.sh`, which git-clones real Eidolon repos — we stop that
# from running by pointing fetch_eidolon's cache at a dead ref via a
# PATH-shadowed fake git that fails fast. The manifest is already
# written to disk by the time sync runs, so we assert on the manifest.

load helpers

setup_fake_git() {
  FAKE_BIN="$BATS_TEST_TMPDIR/fake-bin"
  mkdir -p "$FAKE_BIN"
  cat > "$FAKE_BIN/git" <<'EOF'
#!/usr/bin/env bash
# Fake git: all real git operations succeed as no-ops except clone, which fails.
if [[ "$1" == "clone" ]]; then
  echo "fake-git: clone blocked in tests" >&2
  exit 128
fi
exec /usr/bin/env git-real "$@" 2>/dev/null || true
EOF
  chmod +x "$FAKE_BIN/git"
  export PATH="$FAKE_BIN:$PATH"
}

@test "init: --preset pipeline --non-interactive writes a valid manifest" {
  setup_fake_git
  run eidolons init --preset pipeline --hosts claude-code --non-interactive
  # sync will fail due to fake git — that is expected. Manifest must be written.
  [ -f eidolons.yaml ]
  run cat eidolons.yaml
  [[ "$output" =~ atlas ]]
  [[ "$output" =~ spectra ]]
  [[ "$output" =~ apivr ]]
  [[ "$output" =~ idg ]]
  [[ "$output" =~ version:\ 1 ]]
  [[ "$output" =~ hosts: ]]
  [[ "$output" =~ shared_dispatch:\ false ]]
}

@test "init: --members atlas,spectra writes explicit members" {
  setup_fake_git
  run eidolons init --members atlas,spectra --hosts claude-code --non-interactive
  [ -f eidolons.yaml ]
  grep -q '^  - name: atlas' eidolons.yaml
  grep -q '^  - name: spectra' eidolons.yaml
  # Members not listed must not appear as entries (comment hint can still mention them).
  ! grep -q '^  - name: idg' eidolons.yaml
  ! grep -q '^  - name: apivr' eidolons.yaml
}

@test "init: --non-interactive without --hosts fails when no hosts are auto-detected" {
  run eidolons init --preset minimal --non-interactive
  [ "$status" -ne 0 ]
  [[ "$output" =~ No\ hosts\ auto-detected ]]
}

@test "init: --shared-dispatch flag sets hosts.shared_dispatch: true" {
  setup_fake_git
  run eidolons init --preset minimal --hosts claude-code --shared-dispatch --non-interactive
  [ -f eidolons.yaml ]
  grep -q 'shared_dispatch: true' eidolons.yaml
}

@test "init: --non-interactive without preset/members fails with actionable error" {
  run eidolons init --non-interactive
  [ "$status" -ne 0 ]
  [[ "$output" =~ No\ members\ specified ]]
}

@test "init: fails when eidolons.yaml already exists (no --force)" {
  seed_manifest
  run eidolons init --preset minimal --non-interactive
  [ "$status" -ne 0 ]
  [[ "$output" =~ already\ exists ]]
}

@test "init: --force overwrites existing manifest" {
  setup_fake_git
  seed_manifest
  run eidolons init --preset minimal --hosts claude-code --non-interactive --force
  # Manifest should have been rewritten with init.sh's generated header.
  [ -f eidolons.yaml ]
  grep -q "Generated by eidolons" eidolons.yaml
}

@test "init: rejects bogus member name" {
  run eidolons init --members not-a-real-eidolon --hosts claude-code --non-interactive
  [ "$status" -ne 0 ]
  [[ "$output" =~ not\ found ]]
}

@test "init -h: help prints" {
  run eidolons init -h
  [ "$status" -eq 0 ]
  [[ "$output" =~ Usage:\ eidolons\ init ]]
}
