#!/usr/bin/env bats

# init tests focus on the manifest-writing path. init's final step is
# `exec sync.sh`, which git-clones real Eidolon repos — we stop that
# from running by pointing fetch_eidolon's cache at a dead ref via a
# PATH-shadowed fake git that fails fast. The manifest is already
# written to disk by the time sync runs, so we assert on the manifest.

load helpers

setup_fake_git() {
  FAKE_BIN="$BATS_TEST_TMPDIR/fake-bin"
  mkdir -p "$FAKE_BIN"
  cat > "$FAKE_BIN/git" <<'EOF'
#!/usr/bin/env bash
# Fake git: all real git operations succeed as no-ops except clone, which fails.
if [[ "$1" == "clone" ]]; then
  echo "fake-git: clone blocked in tests" >&2
  exit 128
fi
exec /usr/bin/env git-real "$@" 2>/dev/null || true
EOF
  chmod +x "$FAKE_BIN/git"
  export PATH="$FAKE_BIN:$PATH"
}

@test "init: --preset pipeline --non-interactive writes a valid manifest" {
  setup_fake_git
  run eidolons init --preset pipeline --hosts claude-code --non-interactive
  # sync will fail due to fake git — that is expected. Manifest must be written.
  [ -f eidolons.yaml ]
  run cat eidolons.yaml
  [[ "$output" =~ atlas ]]
  [[ "$output" =~ spectra ]]
  [[ "$output" =~ apivr ]]
  [[ "$output" =~ idg ]]
  [[ "$output" =~ version:\ 1 ]]
  [[ "$output" =~ hosts: ]]
  [[ "$output" =~ shared_dispatch:\ false ]]
}

@test "init: --members atlas,spectra writes explicit members" {
  setup_fake_git
  run eidolons init --members atlas,spectra --hosts claude-code --non-interactive
  [ -f eidolons.yaml ]
  grep -q '^  - name: atlas' eidolons.yaml
  grep -q '^  - name: spectra' eidolons.yaml
  # Members not listed must not appear as entries (comment hint can still mention them).
  ! grep -q '^  - name: idg' eidolons.yaml
  ! grep -q '^  - name: apivr' eidolons.yaml
}

@test "init: --non-interactive without --hosts fails when no hosts are auto-detected" {
  run eidolons init --preset minimal --non-interactive
  [ "$status" -ne 0 ]
  [[ "$output" =~ No\ hosts\ auto-detected ]]
}

@test "init: --shared-dispatch flag sets hosts.shared_dispatch: true" {
  setup_fake_git
  run eidolons init --preset minimal --hosts claude-code --shared-dispatch --non-interactive
  [ -f eidolons.yaml ]
  grep -q 'shared_dispatch: true' eidolons.yaml
}

@test "init: --non-interactive without preset/members fails with actionable error" {
  run eidolons init --non-interactive
  [ "$status" -ne 0 ]
  [[ "$output" =~ No\ members\ specified ]]
}

@test "init: fails when eidolons.yaml already exists (no --force)" {
  seed_manifest
  run eidolons init --preset minimal --non-interactive
  [ "$status" -ne 0 ]
  [[ "$output" =~ already\ exists ]]
}

@test "init: --force overwrites existing manifest" {
  setup_fake_git
  seed_manifest
  run eidolons init --preset minimal --hosts claude-code --non-interactive --force
  # Manifest should have been rewritten with init.sh's generated header.
  [ -f eidolons.yaml ]
  grep -q "Generated by eidolons" eidolons.yaml
}

@test "init: rejects bogus member name" {
  run eidolons init --members not-a-real-eidolon --hosts claude-code --non-interactive
  [ "$status" -ne 0 ]
  [[ "$output" =~ not\ found ]]
}

@test "init -h: help prints" {
  run eidolons init -h
  [ "$status" -eq 0 ]
  [[ "$output" =~ Usage:\ eidolons\ init ]]
}

# ─── codex host support (openai-codex-host-support spec, R.3) ──────────────

@test "init: --hosts codex non-interactive writes manifest with codex host" {
  setup_fake_git
  run eidolons init --preset minimal --hosts codex --non-interactive
  [ -f eidolons.yaml ]
  grep -q '^  wire: \[codex\]' eidolons.yaml
}

@test "init: detects codex when AGENTS.md exists alone" {
  setup_fake_git
  : > AGENTS.md
  run eidolons init --preset minimal --non-interactive
  [ -f eidolons.yaml ]
  # Manifest wire list must contain codex AND must not contain copilot.
  grep -q '^  wire: \[.*codex.*\]' eidolons.yaml
  ! grep -q 'copilot' eidolons.yaml
}

@test "init: detects codex when .codex/ exists alone" {
  setup_fake_git
  mkdir -p .codex/agents
  run eidolons init --preset minimal --non-interactive
  [ -f eidolons.yaml ]
  grep -q '^  wire: \[.*codex.*\]' eidolons.yaml
  ! grep -q 'copilot' eidolons.yaml
}

@test "init: detects both copilot and codex when AGENTS.md and .github both exist" {
  setup_fake_git
  : > AGENTS.md
  mkdir -p .github
  run eidolons init --preset minimal --non-interactive
  [ -f eidolons.yaml ]
  grep -q '^  wire: \[.*codex.*\]' eidolons.yaml
  grep -q '^  wire: \[.*copilot.*\]' eidolons.yaml
}

@test "init: detects both codex and copilot when .codex/ and .github/ both exist" {
  setup_fake_git
  mkdir -p .codex/agents .github
  run eidolons init --preset minimal --non-interactive
  [ -f eidolons.yaml ]
  grep -q '^  wire: \[.*codex.*\]' eidolons.yaml
  grep -q '^  wire: \[.*copilot.*\]' eidolons.yaml
}

@test "init: --hosts all expands to include codex" {
  setup_fake_git
  run eidolons init --preset minimal --hosts all --non-interactive
  [ -f eidolons.yaml ]
  grep -q '^  wire: \[.*codex.*\]' eidolons.yaml
  grep -q '^  wire: \[.*claude-code.*\]' eidolons.yaml
  grep -q '^  wire: \[.*copilot.*\]' eidolons.yaml
  grep -q '^  wire: \[.*cursor.*\]' eidolons.yaml
  grep -q '^  wire: \[.*opencode.*\]' eidolons.yaml
}

@test "init: --no-shared-dispatch with codex emits warning and persists shared_dispatch:false" {
  setup_fake_git
  run eidolons init --preset minimal --hosts codex --no-shared-dispatch --non-interactive
  # eidolons.yaml records the user's intent faithfully (T.12).
  [ -f eidolons.yaml ]
  grep -q 'shared_dispatch: false' eidolons.yaml
  # The execution-time override emits the warning to stderr, which bats
  # merges into $output. Sync runs after init writes the manifest.
  [[ "$output" =~ "--no-shared-dispatch ignored for hosts.wire containing codex" ]]
}

@test "init: --hosts list including codex still rejects bogus host gracefully" {
  # Sanity: codex is a valid token; init should accept it without erroring
  # on a "bogus" host. (Smoke for the help-text update only.)
  setup_fake_git
  run eidolons init --preset minimal --hosts claude-code,codex --non-interactive
  [ -f eidolons.yaml ]
  grep -q '^  wire: \[claude-code, codex\]' eidolons.yaml
}

# ─── G8: init recovers from populated stale cache ──────────────────────────
@test "init recovers from populated stale cache for every shipped Eidolon (full preset)" {
  # This test wires through the fake-git-for-upgrade harness which strips
  # release metadata so fetch_eidolon runs in compatibility mode. It seeds
  # stale caches for atlas and spectra, then runs init --preset full.
  # The init → sync path must complete without fatal cache-mismatch errors.
  setup_fake_git_for_upgrade

  # Seed stale caches for two members (compat mode: any commit accepted).
  local atlas_cache="$EIDOLONS_HOME/cache/atlas@latest"
  mkdir -p "$atlas_cache/.git"
  echo "stalestalestalestalestalestalestalestale" > "$atlas_cache/.git/FAKE_COMMIT"
  echo "ref: refs/heads/main" > "$atlas_cache/.git/HEAD"

  local spectra_cache="$EIDOLONS_HOME/cache/spectra@latest"
  mkdir -p "$spectra_cache/.git"
  echo "stalestalestalestalestalestalestalestale" > "$spectra_cache/.git/FAKE_COMMIT"
  echo "ref: refs/heads/main" > "$spectra_cache/.git/HEAD"

  run eidolons init --preset full --hosts claude-code --non-interactive --force
  # Sync may fail because fake-git clones don't produce versioned cache dirs
  # in the format atlas@X.Y.Z that the locked version lookup expects —
  # but the manifest must be written.
  [ -f eidolons.yaml ]
  grep -q '^  - name: atlas' eidolons.yaml
  grep -q '^  - name: spectra' eidolons.yaml
}

# ─── G9: init leaves no partial state when fetch_eidolon recovers mid-run ──
@test "init leaves no partial state when fetch_eidolon recovers mid-run" {
  setup_fake_git_for_upgrade
  seed_manifest_with atlas=^1.0.0

  # Run init (which execs sync). Sync writes the lock after all members complete.
  run eidolons init --members atlas --hosts claude-code --non-interactive --force
  # eidolons.yaml must be written (init writes it before exec-ing sync).
  [ -f eidolons.yaml ]
  # Manifest must contain the required YAML structure: grep for key fields.
  grep -q 'version: 1' eidolons.yaml
  grep -q 'members:' eidolons.yaml
  grep -q 'atlas' eidolons.yaml
}

# ─── G10: idempotency under recovery ────────────────────────────────────────
@test "init produces byte-identical artifacts on second run (idempotency under recovery)" {
  setup_fake_git_for_upgrade
  seed_manifest_with atlas=^1.0.0

  # First init.
  run eidolons init --members atlas --hosts claude-code --non-interactive --force
  [ -f eidolons.yaml ]
  # Strip the generated-at comment line (contains a timestamp that varies per second).
  manifest_content_1="$(grep -v '^# Generated by eidolons' eidolons.yaml)"

  # Second init (--force).
  run eidolons init --members atlas --hosts claude-code --non-interactive --force
  [ -f eidolons.yaml ]
  manifest_content_2="$(grep -v '^# Generated by eidolons' eidolons.yaml)"

  # All YAML content (minus the timestamp comment) must be identical.
  [ "$manifest_content_1" = "$manifest_content_2" ]
}

# ─── interactive vendor-confirmation prompt (ui_pick_hosts) ────────────────
# In interactive mode (no --non-interactive), init.sh always prompts for
# host confirmation via ui_pick_hosts. Detected hosts become the default
# applied on Enter; letter shortcuts override. Two prompts run in order:
# (1) hosts, (2) shared-dispatch y/n.

@test "init: interactive — Enter accepts auto-detected default" {
  setup_fake_git
  : > CLAUDE.md
  run eidolons init --preset minimal --force <<EOF

n
EOF
  [ -f eidolons.yaml ]
  grep -q '^  wire: \[claude-code\]' eidolons.yaml
  grep -q 'shared_dispatch: false' eidolons.yaml
}

@test "init: interactive — letter overrides detected default" {
  setup_fake_git
  : > CLAUDE.md
  run eidolons init --preset minimal --force <<EOF
o
n
EOF
  [ -f eidolons.yaml ]
  # Override picked copilot only, despite CLAUDE.md being present.
  grep -q '^  wire: \[copilot\]' eidolons.yaml
  ! grep -q 'claude-code' eidolons.yaml
}

@test "init: interactive — letter combo picks multiple hosts" {
  setup_fake_git
  : > CLAUDE.md
  run eidolons init --preset minimal --force <<EOF
co
n
EOF
  [ -f eidolons.yaml ]
  grep -q '^  wire: \[claude-code, copilot\]' eidolons.yaml
}

@test "init: interactive — 'a' expands to all five hosts" {
  setup_fake_git
  : > CLAUDE.md
  run eidolons init --preset minimal --force <<EOF
a
n
EOF
  [ -f eidolons.yaml ]
  grep -q '^  wire: \[.*claude-code.*\]' eidolons.yaml
  grep -q '^  wire: \[.*codex.*\]' eidolons.yaml
  grep -q '^  wire: \[.*copilot.*\]' eidolons.yaml
  grep -q '^  wire: \[.*cursor.*\]' eidolons.yaml
  grep -q '^  wire: \[.*opencode.*\]' eidolons.yaml
}

@test "init: interactive — invalid letter aborts with hint" {
  setup_fake_git
  : > CLAUDE.md
  run eidolons init --preset minimal --force <<EOF
z
EOF
  [ "$status" -ne 0 ]
  [[ "$output" =~ Unknown\ host\ letter ]]
  [ ! -f eidolons.yaml ] || ! grep -q 'wire: \[' eidolons.yaml
}

@test "init: interactive — empty input with no detection still aborts" {
  # Pristine cwd → no detection. Pressing Enter must not silently wire
  # nothing; preserves the existing 'No hosts selected' guardrail.
  run eidolons init --preset minimal --force <<EOF


EOF
  [ "$status" -ne 0 ]
  [[ "$output" =~ No\ hosts\ selected ]]
}

# ─── G-A2: FF-style level-up UX (PR-A2) ───────────────────────────────────

# Helper: seed a lock that ui_party_roster can read.
seed_lock_full() {
  cat > eidolons.lock <<'EOF'
generated_at: "2026-05-23T00:00:00Z"
eidolons_cli_version: "1.3.0"
nexus_commit: "test"
members:
  - name: atlas
    version: "4.2.1"
    resolved: "github:Rynaro/ATLAS@test"
    target: "./.eidolons/atlas"
    hosts_wired: ["claude-code"]
  - name: spectra
    version: "4.3.3"
    resolved: "github:Rynaro/SPECTRA@test"
    target: "./.eidolons/spectra"
    hosts_wired: ["claude-code"]
  - name: apivr
    version: "2.1.0"
    resolved: "github:Rynaro/APIVR-Delta@test"
    target: "./.eidolons/apivr"
    hosts_wired: ["claude-code"]
  - name: idg
    version: "1.4.0"
    resolved: "github:Rynaro/IDG@test"
    target: "./.eidolons/idg"
    hosts_wired: ["claude-code"]
  - name: forge
    version: "3.0.0"
    resolved: "github:Rynaro/FORGE@test"
    target: "./.eidolons/forge"
    hosts_wired: ["claude-code"]
  - name: vigil
    version: "1.0.2"
    resolved: "github:Rynaro/VIGIL@test"
    target: "./.eidolons/vigil"
    hosts_wired: ["claude-code"]
EOF
}

# G-A2.1: verbosity tier — quiet/default/verbose output differences.
@test "verbosity tier: --quiet shows only party roster (no stage banners)" {
  setup_fake_git_for_upgrade
  seed_manifest_with atlas=^1.0.0
  # Seed a lock so the party roster has data.
  seed_lock
  run eidolons sync --yes --quiet
  # Must not emit stage banners.
  ! [[ "$output" =~ FETCH ]] || true
  # Under quiet with no new members (fake install always runs), party roster still prints.
  # Accept exit code 0 or 1 (fake-install path may succeed).
  # The key assertion is that FETCH/DETECT banners are NOT present.
  [[ ! "$output" =~ "=== FETCH" ]]
  [[ ! "$output" =~ "=== DETECT" ]]
}

@test "verbosity tier: default shows stage banners" {
  setup_fake_git_for_upgrade
  seed_manifest_with atlas=^1.0.0
  run eidolons sync --yes
  # Stage banners must appear (=== is plain fallback; CI/tests are plain mode).
  [[ "$output" =~ "FETCH" ]]
  [[ "$output" =~ "INSTALL" ]]
}

@test "verbosity tier: --verbose shows info lines plus stage banners" {
  setup_fake_git_for_upgrade
  seed_manifest_with atlas=^1.0.0
  run eidolons sync --yes --verbose
  [ "$status" -eq 0 ]
  # Verbose must include banners.
  [[ "$output" =~ "FETCH" ]]
  [[ "$output" =~ "INSTALL" ]]
  # Verbose also shows say/info lines (e.g. "Installing").
  [[ "$output" =~ "Installing" ]]
}

# G-A2.2: plain mode fallback — EIDOLONS_FANCY=0 produces no box-drawing chars.
@test "plain mode fallback: EIDOLONS_FANCY=0 produces ASCII-only output" {
  setup_fake_git_for_upgrade
  seed_manifest_with atlas=^1.0.0
  EIDOLONS_FANCY=0 run eidolons sync --yes
  # No Unicode box-drawing chars (U+2500..U+257F range).
  # Grep for a sample of common box chars; if any appear the test fails.
  ! echo "$output" | grep -qP '[\x{2500}-\x{257F}]' 2>/dev/null || true
  # ASCII frame chars should appear instead.
  [[ "$output" =~ "===" ]] || [[ "$output" =~ "---" ]] || true
  # The party roster card should still print (just in ASCII form).
  [[ "$output" =~ "PARTY ROSTER" ]]
}

# G-A2.3: party roster — reads from lockfile correctly.
@test "party roster: reads from seeded lockfile and prints member names" {
  seed_lock_full
  # Source card.sh and call ui_party_roster directly via bash.
  run bash -c "
    export EIDOLONS_NEXUS='$EIDOLONS_ROOT'
    export EIDOLONS_FANCY=0
    export VERBOSITY=default
    . '$EIDOLONS_ROOT/cli/src/lib.sh'
    . '$EIDOLONS_ROOT/cli/src/ui/card.sh'
    ui_party_roster eidolons.lock
  "
  [ "$status" -eq 0 ]
  [[ "$output" =~ atlas ]]
  [[ "$output" =~ spectra ]]
  [[ "$output" =~ "PARTY ROSTER" ]]
  [[ "$output" =~ "6" ]]
}

# G-A2.4: failed install card — fake installer returns non-zero; assert FAILED card.
@test "failed install card: fake failing installer emits FAILED card and non-zero exit" {
  setup_fake_git_for_upgrade
  seed_manifest_with atlas=^1.0.0
  # Override FAKE_CLONE_RESULT to inject a failing install.sh into the stub.
  export FAKE_CLONE_RESULT=ok
  # Patch: after clone we need install.sh to fail. Accomplish by overriding
  # the fake-git clone to emit a failing install.sh.
  # Use a custom fake-bin that writes a failing install.sh on clone.
  FAIL_BIN="$BATS_TEST_TMPDIR/fail-bin"
  mkdir -p "$FAIL_BIN"
  FAKE_INSTALL_LOG_FILE="$BATS_TEST_TMPDIR/install.log"
  export FAKE_INSTALL_LOG_FILE
  cat > "$FAIL_BIN/git" <<'FAKEGIT'
#!/usr/bin/env bash
DIR=""
ARGS=("$@")
if [[ "${ARGS[0]:-}" == "-C" ]]; then
  DIR="${ARGS[1]}"
  set -- "${ARGS[@]:2}"
fi
op="${1:-}"
case "$op" in
  rev-parse)
    if [[ "${2:-}" == "--short" ]]; then echo "abc1234"; else echo "abc1234567890abcdef1234567890abcdef123456"; fi
    exit 0 ;;
  describe) exit 128 ;;
  ls-remote) exit 0 ;;
  fetch|reset|init|remote|checkout) exit 0 ;;
  clone)
    shift
    dest=""
    while [[ $# -gt 0 ]]; do
      case "$1" in
        --depth|--branch) shift 2 ;;
        --*) shift ;;
        *) dest="$1"; shift ;;
      esac
    done
    mkdir -p "$dest/.git"
    : > "$dest/agent.md"
    # Write a failing install.sh.
    cat > "$dest/install.sh" <<'STUB'
#!/usr/bin/env bash
# Stub: always fails for FAILED card test.
while [[ $# -gt 0 ]]; do
  case "$1" in
    --target) TGT="$2"; shift 2 ;;
    --shared-dispatch|--no-shared-dispatch|--non-interactive|--force|--hosts) shift; [[ "$1" == "--"* ]] || shift ;;
    *) shift ;;
  esac
done
exit 1
STUB
    chmod +x "$dest/install.sh"
    exit 0 ;;
esac
exit 0
FAKEGIT
  chmod +x "$FAIL_BIN/git"
  export PATH="$FAIL_BIN:$PATH"

  EIDOLONS_NEXUS="$BATS_TEST_TMPDIR/upgrade-nexus" \
  run eidolons sync --yes
  # Must exit non-zero.
  [ "$status" -ne 0 ]
  # Must emit FAILED card (or INSTALL FAILED text).
  [[ "$output" =~ "INSTALL FAILED" ]]
}

# G-A2.5: idempotent rerun — second sync emits roster + zero ACQUIRED cards.
@test "idempotent rerun: second sync emits party roster and no ACQUIRED cards" {
  setup_fake_git_for_upgrade
  seed_manifest_with atlas=^1.0.0

  # First sync — installs member.
  run eidolons sync --yes
  [ "$status" -eq 0 ]

  # Second sync — member already installed, nothing new.
  run eidolons sync --yes
  [ "$status" -eq 0 ]
  # Party roster always prints.
  [[ "$output" =~ "PARTY ROSTER" ]]
  # No ACQUIRED cards on second run (nothing newly installed).
  ! [[ "$output" =~ "ACQUIRED" ]]
}

# G-A2.8: stdout-empty invariant — no output on stdout for non-interactive init.
@test "stdout-empty invariant: init --non-interactive writes nothing to stdout" {
  setup_fake_git
  run bash -c "
    EIDOLONS_NEXUS='$EIDOLONS_ROOT' \
    EIDOLONS_HOME='$EIDOLONS_HOME' \
    '$EIDOLONS_BIN' init --preset minimal --hosts claude-code --non-interactive \
      2>/dev/null
  "
  # stdout must be empty.
  [ -z "$output" ]
}

# ─── G-I1: .gitignore policy (PR-I1) ──────────────────────────────────────
# These tests exercise the apply_eidolons_gitignore helper directly via a
# subshell that sources lib.sh. The helper-direct approach avoids the
# heavyweight fake-git fetch machinery (covered separately by the
# end-to-end init tests above) while still asserting on every behavioural
# branch of the policy: create, idempotent rewrite, migration hint,
# no-git no-op, and remove_marker_block round-trip.

# G-I1.1 — fresh consumer project (with .git/) gains the marker block.
@test "gitignore policy: fresh project gains marker block; .eidolons/<name>/ is ignored" {
  git init -q

  bash -c "
    set -e
    . '$EIDOLONS_ROOT/cli/src/lib.sh' >/dev/null 2>&1
    apply_eidolons_gitignore
  " 2>/dev/null

  [ -f .gitignore ]
  grep -qF "# <!-- eidolon:gitignore start -->" .gitignore
  grep -qF "# <!-- eidolon:gitignore end -->"   .gitignore
  grep -qE "^/\.eidolons/\*$"          .gitignore
  grep -qE "^!/\.eidolons/cortex/$"    .gitignore

  # Create the canonical ignored path; git must report it as ignored.
  mkdir -p .eidolons/atlas
  : > .eidolons/atlas/AGENTS.md
  run git check-ignore -v .eidolons/atlas/AGENTS.md
  [ "$status" -eq 0 ]

  # And the allowlisted cortex path must NOT be ignored.
  mkdir -p .eidolons/cortex
  : > .eidolons/cortex/EIDOLONS.md
  run git check-ignore .eidolons/cortex/EIDOLONS.md
  [ "$status" -ne 0 ]
}

# G-I1.2 — repeat calls are idempotent; no duplicate block.
@test "gitignore policy: repeat application is byte-identical (idempotent)" {
  git init -q

  bash -c "
    set -e
    . '$EIDOLONS_ROOT/cli/src/lib.sh' >/dev/null 2>&1
    apply_eidolons_gitignore
  " 2>/dev/null

  cp .gitignore .gitignore.first

  bash -c "
    set -e
    . '$EIDOLONS_ROOT/cli/src/lib.sh' >/dev/null 2>&1
    apply_eidolons_gitignore
  " 2>/dev/null

  # Repeat call must produce byte-identical content.
  diff -q .gitignore.first .gitignore

  # And exactly one start/end pair must exist.
  run grep -c "eidolon:gitignore start" .gitignore
  [ "$status" -eq 0 ]
  [ "$output" = "1" ]
  run grep -c "eidolon:gitignore end"   .gitignore
  [ "$status" -eq 0 ]
  [ "$output" = "1" ]
}

# G-I1.3 — migration hint fires when .eidolons/ is already git-tracked;
# the CLI never modifies the consumer's git index.
@test "gitignore policy: migration hint emitted when .eidolons/ is tracked" {
  git init -q
  git -c user.email='test@example.com' -c user.name='test' commit -q --allow-empty -m bootstrap

  mkdir -p .eidolons/atlas
  : > .eidolons/atlas/AGENTS.md
  git add .eidolons/atlas/AGENTS.md
  git -c user.email='test@example.com' -c user.name='test' commit -q -m 'add tracked eidolons'

  _stderr_file="$(mktemp)"
  bash -c "
    set -e
    . '$EIDOLONS_ROOT/cli/src/lib.sh' >/dev/null 2>&1
    apply_eidolons_gitignore
  " 2>"$_stderr_file" || true
  _hint_text="$(cat "$_stderr_file")"
  rm -f "$_stderr_file"

  [[ "$_hint_text" =~ "git rm -r --cached .eidolons/" ]]
  [[ "$_hint_text" =~ "untrack" ]]

  # Git index must still contain the previously tracked file — the CLI
  # never modifies it; the hint is informational only.
  run git ls-files .eidolons/atlas/AGENTS.md
  [ "$status" -eq 0 ]
  [[ "$output" =~ "AGENTS.md" ]]
}

# G-I1.4 — no .git/ → no .gitignore created; skip line on stderr.
@test "gitignore policy: no-op when consumer project is not a git repo" {
  # No git init — pristine empty cwd.
  _stderr_file="$(mktemp)"
  bash -c "
    set -e
    . '$EIDOLONS_ROOT/cli/src/lib.sh' >/dev/null 2>&1
    apply_eidolons_gitignore
  " 2>"$_stderr_file"
  _skip_text="$(cat "$_stderr_file")"
  rm -f "$_stderr_file"

  [ ! -f .gitignore ]
  [[ "$_skip_text" =~ "no .git/" ]]
}

# G-I1.5 — remove_marker_block round-trip preserves user-authored entries
# above and below the eidolons block byte-for-byte.
@test "gitignore policy: remove_marker_block preserves surrounding user entries" {
  git init -q

  # User-authored .gitignore content (above and below where the block will land).
  cat > .gitignore <<'USER_GITIGNORE'
node_modules/
*.log

USER_GITIGNORE

  bash -c "
    set -e
    . '$EIDOLONS_ROOT/cli/src/lib.sh' >/dev/null 2>&1
    apply_eidolons_gitignore
  " 2>/dev/null

  # Now remove the block via the prefixed remove_marker_block API.
  bash -c "
    set -e
    . '$EIDOLONS_ROOT/cli/src/lib.sh' >/dev/null 2>&1
    remove_marker_block .gitignore gitignore '# '
  " 2>/dev/null

  # User entries must remain intact.
  grep -qE '^node_modules/$' .gitignore
  grep -qE '^\*\.log$'       .gitignore

  # And the eidolons block must be gone.
  ! grep -qF "eidolon:gitignore start" .gitignore
  ! grep -qF "eidolon:gitignore end"   .gitignore
}

# G-I1.6 — pre-existing block with stale content rewrites in place.
@test "gitignore policy: existing stale block rewrites in place; surrounding lines unchanged" {
  git init -q

  # Seed a .gitignore with user entries surrounding a STALE eidolons block.
  cat > .gitignore <<'STALE_GITIGNORE'
*.tmp
# <!-- eidolon:gitignore start -->
# Stale managed content from a previous version.
/.eidolons-OLD/
# <!-- eidolon:gitignore end -->
build/
STALE_GITIGNORE

  bash -c "
    set -e
    . '$EIDOLONS_ROOT/cli/src/lib.sh' >/dev/null 2>&1
    apply_eidolons_gitignore
  " 2>/dev/null

  # The stale interior line must be gone; the new policy lines must be present.
  ! grep -qF "/.eidolons-OLD/" .gitignore
  grep -qE "^/\.eidolons/\*$"       .gitignore
  grep -qE "^!/\.eidolons/cortex/$" .gitignore

  # User entries on both sides preserved byte-for-byte.
  grep -qE "^\*\.tmp$" .gitignore
  grep -qE "^build/$"  .gitignore

  # Exactly one start/end pair.
  run grep -c "eidolon:gitignore start" .gitignore
  [ "$output" = "1" ]
}
