#!/usr/bin/env bats

# init tests focus on the manifest-writing path. init's final step is
# `exec sync.sh`, which git-clones real Eidolon repos — we stop that
# from running by pointing fetch_eidolon's cache at a dead ref via a
# PATH-shadowed fake git that fails fast. The manifest is already
# written to disk by the time sync runs, so we assert on the manifest.

load helpers

setup_fake_git() {
  FAKE_BIN="$BATS_TEST_TMPDIR/fake-bin"
  mkdir -p "$FAKE_BIN"
  cat > "$FAKE_BIN/git" <<'EOF'
#!/usr/bin/env bash
# Fake git: all real git operations succeed as no-ops except clone, which fails.
if [[ "$1" == "clone" ]]; then
  echo "fake-git: clone blocked in tests" >&2
  exit 128
fi
exec /usr/bin/env git-real "$@" 2>/dev/null || true
EOF
  chmod +x "$FAKE_BIN/git"
  export PATH="$FAKE_BIN:$PATH"
}

@test "init: --preset pipeline --non-interactive writes a valid manifest" {
  setup_fake_git
  run eidolons init --preset pipeline --hosts claude-code --non-interactive
  # sync will fail due to fake git — that is expected. Manifest must be written.
  [ -f eidolons.yaml ]
  run cat eidolons.yaml
  [[ "$output" =~ atlas ]]
  [[ "$output" =~ spectra ]]
  [[ "$output" =~ apivr ]]
  [[ "$output" =~ idg ]]
  [[ "$output" =~ version:\ 1 ]]
  [[ "$output" =~ hosts: ]]
  [[ "$output" =~ shared_dispatch:\ false ]]
}

@test "init: --members atlas,spectra writes explicit members" {
  setup_fake_git
  run eidolons init --members atlas,spectra --hosts claude-code --non-interactive
  [ -f eidolons.yaml ]
  grep -q '^  - name: atlas' eidolons.yaml
  grep -q '^  - name: spectra' eidolons.yaml
  # Members not listed must not appear as entries (comment hint can still mention them).
  ! grep -q '^  - name: idg' eidolons.yaml
  ! grep -q '^  - name: apivr' eidolons.yaml
}

@test "init: --non-interactive without --hosts fails when no hosts are auto-detected" {
  run eidolons init --preset minimal --non-interactive
  [ "$status" -ne 0 ]
  [[ "$output" =~ No\ hosts\ auto-detected ]]
}

@test "init: --shared-dispatch flag sets hosts.shared_dispatch: true" {
  setup_fake_git
  run eidolons init --preset minimal --hosts claude-code --shared-dispatch --non-interactive
  [ -f eidolons.yaml ]
  grep -q 'shared_dispatch: true' eidolons.yaml
}

@test "init: --non-interactive without preset/members fails with actionable error" {
  run eidolons init --non-interactive
  [ "$status" -ne 0 ]
  [[ "$output" =~ No\ members\ specified ]]
}

@test "init: fails when eidolons.yaml already exists (no --force)" {
  seed_manifest
  run eidolons init --preset minimal --non-interactive
  [ "$status" -ne 0 ]
  [[ "$output" =~ already\ exists ]]
}

@test "init: --force overwrites existing manifest" {
  setup_fake_git
  seed_manifest
  run eidolons init --preset minimal --hosts claude-code --non-interactive --force
  # Manifest should have been rewritten with init.sh's generated header.
  [ -f eidolons.yaml ]
  grep -q "Generated by eidolons" eidolons.yaml
}

@test "init: rejects bogus member name" {
  run eidolons init --members not-a-real-eidolon --hosts claude-code --non-interactive
  [ "$status" -ne 0 ]
  [[ "$output" =~ not\ found ]]
}

@test "init -h: help prints" {
  run eidolons init -h
  [ "$status" -eq 0 ]
  [[ "$output" =~ Usage:\ eidolons\ init ]]
}

# ─── codex host support (openai-codex-host-support spec, R.3) ──────────────

@test "init: --hosts codex non-interactive writes manifest with codex host" {
  setup_fake_git
  run eidolons init --preset minimal --hosts codex --non-interactive
  [ -f eidolons.yaml ]
  grep -q '^  wire: \[codex\]' eidolons.yaml
}

@test "init: detects codex when AGENTS.md exists alone" {
  setup_fake_git
  : > AGENTS.md
  run eidolons init --preset minimal --non-interactive
  [ -f eidolons.yaml ]
  # Manifest wire list must contain codex AND must not contain copilot.
  grep -q '^  wire: \[.*codex.*\]' eidolons.yaml
  ! grep -q 'copilot' eidolons.yaml
}

@test "init: detects codex when .codex/ exists alone" {
  setup_fake_git
  mkdir -p .codex/agents
  run eidolons init --preset minimal --non-interactive
  [ -f eidolons.yaml ]
  grep -q '^  wire: \[.*codex.*\]' eidolons.yaml
  ! grep -q 'copilot' eidolons.yaml
}

@test "init: detects both copilot and codex when AGENTS.md and .github both exist" {
  setup_fake_git
  : > AGENTS.md
  mkdir -p .github
  run eidolons init --preset minimal --non-interactive
  [ -f eidolons.yaml ]
  grep -q '^  wire: \[.*codex.*\]' eidolons.yaml
  grep -q '^  wire: \[.*copilot.*\]' eidolons.yaml
}

@test "init: detects both codex and copilot when .codex/ and .github/ both exist" {
  setup_fake_git
  mkdir -p .codex/agents .github
  run eidolons init --preset minimal --non-interactive
  [ -f eidolons.yaml ]
  grep -q '^  wire: \[.*codex.*\]' eidolons.yaml
  grep -q '^  wire: \[.*copilot.*\]' eidolons.yaml
}

@test "init: --hosts all expands to include codex" {
  setup_fake_git
  run eidolons init --preset minimal --hosts all --non-interactive
  [ -f eidolons.yaml ]
  grep -q '^  wire: \[.*codex.*\]' eidolons.yaml
  grep -q '^  wire: \[.*claude-code.*\]' eidolons.yaml
  grep -q '^  wire: \[.*copilot.*\]' eidolons.yaml
  grep -q '^  wire: \[.*cursor.*\]' eidolons.yaml
  grep -q '^  wire: \[.*opencode.*\]' eidolons.yaml
}

@test "init: --no-shared-dispatch with codex emits warning and persists shared_dispatch:false" {
  setup_fake_git
  run eidolons init --preset minimal --hosts codex --no-shared-dispatch --non-interactive
  # eidolons.yaml records the user's intent faithfully (T.12).
  [ -f eidolons.yaml ]
  grep -q 'shared_dispatch: false' eidolons.yaml
  # The execution-time override emits the warning to stderr, which bats
  # merges into $output. Sync runs after init writes the manifest.
  [[ "$output" =~ "--no-shared-dispatch ignored for hosts.wire containing codex" ]]
}

@test "init: --hosts list including codex still rejects bogus host gracefully" {
  # Sanity: codex is a valid token; init should accept it without erroring
  # on a "bogus" host. (Smoke for the help-text update only.)
  setup_fake_git
  run eidolons init --preset minimal --hosts claude-code,codex --non-interactive
  [ -f eidolons.yaml ]
  grep -q '^  wire: \[claude-code, codex\]' eidolons.yaml
}

# ─── interactive vendor-confirmation prompt (ui_pick_hosts) ────────────────
# In interactive mode (no --non-interactive), init.sh always prompts for
# host confirmation via ui_pick_hosts. Detected hosts become the default
# applied on Enter; letter shortcuts override. Two prompts run in order:
# (1) hosts, (2) shared-dispatch y/n.

@test "init: interactive — Enter accepts auto-detected default" {
  setup_fake_git
  : > CLAUDE.md
  run eidolons init --preset minimal --force <<EOF

n
EOF
  [ -f eidolons.yaml ]
  grep -q '^  wire: \[claude-code\]' eidolons.yaml
  grep -q 'shared_dispatch: false' eidolons.yaml
}

@test "init: interactive — letter overrides detected default" {
  setup_fake_git
  : > CLAUDE.md
  run eidolons init --preset minimal --force <<EOF
o
n
EOF
  [ -f eidolons.yaml ]
  # Override picked copilot only, despite CLAUDE.md being present.
  grep -q '^  wire: \[copilot\]' eidolons.yaml
  ! grep -q 'claude-code' eidolons.yaml
}

@test "init: interactive — letter combo picks multiple hosts" {
  setup_fake_git
  : > CLAUDE.md
  run eidolons init --preset minimal --force <<EOF
co
n
EOF
  [ -f eidolons.yaml ]
  grep -q '^  wire: \[claude-code, copilot\]' eidolons.yaml
}

@test "init: interactive — 'a' expands to all five hosts" {
  setup_fake_git
  : > CLAUDE.md
  run eidolons init --preset minimal --force <<EOF
a
n
EOF
  [ -f eidolons.yaml ]
  grep -q '^  wire: \[.*claude-code.*\]' eidolons.yaml
  grep -q '^  wire: \[.*codex.*\]' eidolons.yaml
  grep -q '^  wire: \[.*copilot.*\]' eidolons.yaml
  grep -q '^  wire: \[.*cursor.*\]' eidolons.yaml
  grep -q '^  wire: \[.*opencode.*\]' eidolons.yaml
}

@test "init: interactive — invalid letter aborts with hint" {
  setup_fake_git
  : > CLAUDE.md
  run eidolons init --preset minimal --force <<EOF
z
EOF
  [ "$status" -ne 0 ]
  [[ "$output" =~ Unknown\ host\ letter ]]
  [ ! -f eidolons.yaml ] || ! grep -q 'wire: \[' eidolons.yaml
}

@test "init: interactive — empty input with no detection still aborts" {
  # Pristine cwd → no detection. Pressing Enter must not silently wire
  # nothing; preserves the existing 'No hosts selected' guardrail.
  run eidolons init --preset minimal --force <<EOF


EOF
  [ "$status" -ne 0 ]
  [[ "$output" =~ No\ hosts\ selected ]]
}
