#!/usr/bin/env bats
# cli/tests/migrate-stamp.bats — bats coverage for eidolons migrate-stamp (R2B-5)

load helpers

# Helper: set up a fully-passing project state (checks 1-11 satisfied)
_seed_migrate_base() {
  local nexus_ver
  nexus_ver="$(cat "$EIDOLONS_ROOT/VERSION")"

  cat > eidolons.yaml <<EOF
# eidolons.yaml — per-project manifest
# Generated by eidolons v${nexus_ver} at 2026-05-24T12:00:00Z
# Docs: https://github.com/Rynaro/eidolons/blob/main/docs/getting-started.md

version: 1
hosts:
  wire: [claude-code]
members:
  - name: atlas
    version: "^1.0.0"
    source: github:Rynaro/ATLAS
EOF

  cat > eidolons.lock <<EOF
generated_at: "2026-05-24T12:00:00Z"
eidolons_cli_version: "${nexus_ver}"
nexus_commit: "test"
members:
  - name: atlas
    version: "1.0.0"
    resolved: "github:Rynaro/ATLAS@test"
    target: "./.eidolons/atlas"
    hosts_wired: ["claude-code"]
EOF
}

# Helper: seed stale-stamped files (stamps say 1.0.0, nexus is current)
_seed_stale_stamps() {
  cat > eidolons.yaml <<'EOF'
# eidolons.yaml — per-project manifest
# Generated by eidolons v1.0.0 at 2026-05-24T12:00:00Z
# Docs: https://github.com/Rynaro/eidolons/blob/main/docs/getting-started.md

version: 1
hosts:
  wire: [claude-code]
members:
  - name: atlas
    version: "^1.0.0"
    source: github:Rynaro/ATLAS
EOF

  cat > eidolons.lock <<'EOF'
generated_at: "2026-05-24T12:00:00Z"
eidolons_cli_version: "1.0.0"
nexus_commit: "test"
members:
  - name: atlas
    version: "1.0.0"
    resolved: "github:Rynaro/ATLAS@test"
    target: "./.eidolons/atlas"
    hosts_wired: ["claude-code"]
EOF
}

# G-R2B-5.1 — rewrites stale stamps
@test "migrate-stamp: rewrites stale stamps" {
  _seed_stale_stamps
  local nexus_ver
  nexus_ver="$(cat "$EIDOLONS_ROOT/VERSION")"

  run eidolons migrate-stamp
  [ "$status" -eq 0 ]
  # ok lines should mention "Rewrote"
  [[ "$output" =~ Rewrote ]]
  # eidolons.yaml line 2 should now have the nexus version
  local yaml_line2
  yaml_line2="$(sed -n '2p' eidolons.yaml)"
  [[ "$yaml_line2" =~ "eidolons v${nexus_ver} at" ]]
  # eidolons.lock should have the nexus version
  [[ "$(grep eidolons_cli_version eidolons.lock)" =~ "${nexus_ver}" ]]
}

# G-R2B-5.2 — idempotent no-op
@test "migrate-stamp: idempotent no-op" {
  _seed_migrate_base
  local nexus_ver
  nexus_ver="$(cat "$EIDOLONS_ROOT/VERSION")"

  run eidolons migrate-stamp
  [ "$status" -eq 0 ]
  [[ "$output" =~ "already match nexus" ]]
  # Files unchanged
  [[ "$(grep eidolons_cli_version eidolons.lock)" =~ "${nexus_ver}" ]]
}

# G-R2B-5.3 — dry-run preserves files
@test "migrate-stamp: dry-run preserves files" {
  _seed_stale_stamps

  # Record original lock content
  local orig_lock
  orig_lock="$(cat eidolons.lock)"

  run eidolons migrate-stamp --dry-run
  [ "$status" -eq 0 ]
  [[ "$output" =~ "dry-run" ]]
  # Files must remain unchanged
  local new_lock
  new_lock="$(cat eidolons.lock)"
  [ "$orig_lock" = "$new_lock" ]
  # yaml line 2 still says 1.0.0
  local yaml_line2
  yaml_line2="$(sed -n '2p' eidolons.yaml)"
  [[ "$yaml_line2" =~ "v1.0.0" ]]
}

# G-R2B-5.4 — mode preserved at 0644
@test "migrate-stamp: mode preserved at 0644" {
  _seed_stale_stamps

  run eidolons migrate-stamp
  [ "$status" -eq 0 ]

  # Check mode — use stat with BSD or GNU variant
  if stat -f '%Lp' eidolons.lock >/dev/null 2>&1; then
    # BSD/macOS
    local lock_mode yaml_mode
    lock_mode="$(stat -f '%Lp' eidolons.lock)"
    yaml_mode="$(stat -f '%Lp' eidolons.yaml)"
  else
    # GNU/Linux
    local lock_mode yaml_mode
    lock_mode="$(stat -c '%a' eidolons.lock)"
    yaml_mode="$(stat -c '%a' eidolons.yaml)"
  fi
  [ "$lock_mode" = "644" ]
  [ "$yaml_mode" = "644" ]
}

# G-R2B-5.5 — timestamp preserved in eidolons.yaml
@test "migrate-stamp: timestamp preserved" {
  _seed_stale_stamps
  # The timestamp in the seeded file is "2026-05-24T12:00:00Z"

  run eidolons migrate-stamp
  [ "$status" -eq 0 ]

  local yaml_line2
  yaml_line2="$(sed -n '2p' eidolons.yaml)"
  # Timestamp portion must still be present
  [[ "$yaml_line2" =~ "at 2026-05-24T12:00:00Z" ]]
  # But version must have changed from 1.0.0
  [[ ! "$yaml_line2" =~ "v1.0.0" ]]
}

# Missing manifest+lock — degrade gracefully
@test "migrate-stamp: missing manifest and lock degrade gracefully" {
  # No eidolons.yaml or eidolons.lock in the project dir.
  run eidolons migrate-stamp
  [ "$status" -eq 0 ]
  [[ "$output" =~ "already match nexus" ]]
}

# --help prints usage
@test "migrate-stamp -h: help prints" {
  run eidolons migrate-stamp -h
  [ "$status" -eq 0 ]
  [[ "$output" =~ "Usage: eidolons migrate-stamp" ]]
}
