#!/usr/bin/env bash
# eidolons init — bootstrap a project with Eidolons
# ═══════════════════════════════════════════════════════════════════════════

set -euo pipefail
SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
. "$SELF_DIR/lib.sh"

PRESET=""
MEMBERS=""
HOSTS="auto"
NON_INTERACTIVE=false
FORCE=false

usage() {
  cat <<EOF
eidolons init — initialize a project with Eidolons

Usage: eidolons init [OPTIONS]

Options:
  --preset NAME         Use a named preset from the roster (minimal, pipeline, full, ...)
                        Run 'eidolons list --presets' to see all.
  --members LIST        Comma-separated list of Eidolon names.
                        Mutually exclusive with --preset.
  --hosts LIST          Comma-separated: claude-code,copilot,cursor,opencode,all
                        Default: auto (detect from project)
  --force               Overwrite existing eidolons.yaml without prompting
  --non-interactive     Fail on any prompt. Requires --preset or --members.
  -h, --help            Show this help

Behavior:
  - Detects whether the project is empty (greenfield) or populated (brownfield).
  - If interactive: prompts for members and confirms host wiring.
  - Writes eidolons.yaml + eidolons.lock to the project root.
  - Installs each chosen Eidolon by calling its own install.sh.
  - Works safely in brownfield projects: appends to existing AGENTS.md / CLAUDE.md.

EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --preset)           PRESET="$2"; shift 2 ;;
    --members)          MEMBERS="$2"; shift 2 ;;
    --hosts)            HOSTS="$2"; shift 2 ;;
    --force)            FORCE=true; shift ;;
    --non-interactive)  NON_INTERACTIVE=true; shift ;;
    -h|--help)          usage; exit 0 ;;
    *)                  echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
  esac
done

# ─── Detect greenfield vs brownfield ──────────────────────────────────────
PROJECT_STATE="greenfield"
if [[ -n "$(ls -A . 2>/dev/null)" ]]; then
  PROJECT_STATE="brownfield"
fi
say "Project state: $PROJECT_STATE ($(pwd))"

# ─── Idempotency check ────────────────────────────────────────────────────
if manifest_exists && [[ "$FORCE" != "true" ]]; then
  warn "eidolons.yaml already exists. Use --force to overwrite, or 'eidolons add/sync' instead."
  exit 1
fi

# ─── Resolve members ──────────────────────────────────────────────────────
resolve_members() {
  if [[ -n "$PRESET" ]]; then
    roster_preset_members "$PRESET" | paste -sd,
    return
  fi
  if [[ -n "$MEMBERS" ]]; then
    echo "$MEMBERS"
    return
  fi
  if [[ "$NON_INTERACTIVE" == "true" ]]; then
    die "No members specified. Use --preset or --members when --non-interactive."
  fi
  # Interactive picker
  echo ""
  echo "${BOLD}Available presets:${RESET}"
  yaml_to_json "$ROSTER_FILE" | jq -r '.presets | to_entries[] | "  \(.key) — \(.value.description)"'
  echo ""
  echo "${BOLD}Available Eidolons:${RESET}"
  yaml_to_json "$ROSTER_FILE" | jq -r '.eidolons[] | "  \(.name) — \(.methodology.summary)"'
  echo ""
  read -rp "Enter preset name, or comma-separated members: " choice
  if roster_presets | grep -Fxq "$choice"; then
    roster_preset_members "$choice" | paste -sd,
  else
    echo "$choice"
  fi
}

MEMBERS_CSV="$(resolve_members)"
[[ -z "$MEMBERS_CSV" ]] && die "No members resolved. Aborting."
IFS=',' read -ra MEMBERS_ARR <<< "$MEMBERS_CSV"
say "Members: ${MEMBERS_ARR[*]}"

# Validate every member exists in the roster
for m in "${MEMBERS_ARR[@]}"; do
  m="$(echo "$m" | xargs)"  # trim
  roster_get "$m" >/dev/null
done

# ─── Resolve hosts ────────────────────────────────────────────────────────
if [[ "$HOSTS" == "auto" ]]; then
  if [[ "$PROJECT_STATE" == "greenfield" ]]; then
    # Greenfield: wire every major host so the project is host-agnostic from day one.
    HOSTS="claude-code,copilot,cursor,opencode"
    info "Greenfield project — wiring all major hosts"
  else
    detected="$(detect_hosts | paste -sd,)"
    if [[ -z "$detected" ]]; then
      warn "No hosts detected. Defaulting to claude-code + copilot."
      HOSTS="claude-code,copilot"
    else
      HOSTS="$detected"
      info "Detected hosts: $HOSTS"
    fi
  fi
fi

# ─── Write eidolons.yaml ─────────────────────────────────────────────────
say "Writing $PROJECT_MANIFEST"
{
  echo "# eidolons.yaml — per-project manifest"
  echo "# Generated by eidolons v${EIDOLONS_VERSION:-1.0.0} at $(date -u +%FT%TZ)"
  echo "# Docs: https://github.com/Rynaro/eidolons/blob/main/docs/getting-started.md"
  echo ""
  echo "version: 1"
  echo "hosts:"
  echo "  wire: [$(echo "$HOSTS" | sed 's/,/, /g')]"
  echo ""
  echo "members:"
  for m in "${MEMBERS_ARR[@]}"; do
    m="$(echo "$m" | xargs)"
    entry="$(roster_get "$m")"
    latest="$(echo "$entry" | jq -r '.versions.latest')"
    repo="$(echo "$entry" | jq -r '.source.repo')"
    echo "  - name: $m"
    echo "    version: \"^$latest\""
    echo "    source: github:$repo"
  done
  echo ""
  echo "# Optional documentation of the intended pipeline:"
  echo "# composition:"
  echo "#   pipeline: [atlas, spectra, apivr, idg]"
} > "$PROJECT_MANIFEST"

ok "$PROJECT_MANIFEST written"

# ─── Delegate actual install to `eidolons sync` ──────────────────────────
say "Running sync to install members"
exec bash "$CLI_SRC/sync.sh" ${NON_INTERACTIVE:+--non-interactive}
