#!/usr/bin/env bash
# eidolons migrate-stamp — rewrite version stamps in eidolons.yaml and eidolons.lock
# ═══════════════════════════════════════════════════════════════════════════
#
# Idempotent: no-op when both stamps already match the current nexus VERSION.
# All log output to stderr. Bash 3.2 safe.

set -euo pipefail
SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
. "$SELF_DIR/lib.sh"

usage() {
  cat <<EOF
eidolons migrate-stamp — rewrite version stamps to match the current nexus VERSION

Usage: eidolons migrate-stamp [OPTIONS]

Options:
  --dry-run     Show what would be rewritten; do not modify files
  -h, --help    Show this help

Behaviour:
  - Reads VERSION from \$EIDOLONS_NEXUS/VERSION.
  - Rewrites eidolons.yaml line 2 header comment to match.
  - Rewrites eidolons.lock 'eidolons_cli_version:' field to match.
  - Idempotent: no-op when both files already match.
  - No git operations: user commits the changes themselves.
EOF
}

DRY_RUN=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)   DRY_RUN=true; shift ;;
    -h|--help)   usage; exit 0 ;;
    *)           echo "Unknown option: $1" >&2; exit 2 ;;
  esac
done

_target="$(read_nexus_version 2>/dev/null || echo "0.0.0-dev")"
if [[ "$_target" == "0.0.0-dev" ]]; then
  die "Cannot read nexus VERSION from $NEXUS/VERSION; aborting."
fi

_changed=false

# ─── eidolons.yaml header comment ────────────────────────────────────────
if [[ -f "$PROJECT_MANIFEST" ]]; then
  _yaml_stamp="$(sed -n '2p' "$PROJECT_MANIFEST" 2>/dev/null \
    | sed -E 's/^# Generated by eidolons v([^ ]+) at .*$/\1/' || true)"
  if [[ -n "$_yaml_stamp" ]] && [[ "$_yaml_stamp" != "$_target" ]]; then
    if [[ "$DRY_RUN" == "true" ]]; then
      info "  [dry-run] would rewrite $PROJECT_MANIFEST stamp '$_yaml_stamp' → '$_target'"
    else
      _tmp="$(mktemp)"
      sed -E "2s/(# Generated by eidolons v)[^ ]+( at .*)/\1$_target\2/" "$PROJECT_MANIFEST" > "$_tmp"
      mv "$_tmp" "$PROJECT_MANIFEST"
      chmod 0644 "$PROJECT_MANIFEST" 2>/dev/null || true
      ok "Rewrote $PROJECT_MANIFEST stamp '$_yaml_stamp' → '$_target'"
    fi
    _changed=true
  fi
fi

# ─── eidolons.lock eidolons_cli_version field ────────────────────────────
if [[ -f "$PROJECT_LOCK" ]]; then
  _lock_stamp="$(yaml_to_json "$PROJECT_LOCK" 2>/dev/null \
    | jq -r '.eidolons_cli_version // empty' 2>/dev/null || true)"
  if [[ -n "$_lock_stamp" ]] && [[ "$_lock_stamp" != "$_target" ]]; then
    if [[ "$DRY_RUN" == "true" ]]; then
      info "  [dry-run] would rewrite $PROJECT_LOCK eidolons_cli_version '$_lock_stamp' → '$_target'"
    else
      _tmp="$(mktemp)"
      sed -E "s/^(eidolons_cli_version: *\")[^\"]+(\")/\1$_target\2/" "$PROJECT_LOCK" > "$_tmp"
      mv "$_tmp" "$PROJECT_LOCK"
      chmod 0644 "$PROJECT_LOCK" 2>/dev/null || true
      ok "Rewrote $PROJECT_LOCK eidolons_cli_version '$_lock_stamp' → '$_target'"
    fi
    _changed=true
  fi
fi

if [[ "$_changed" == "false" ]]; then
  ok "Version stamps already match nexus ($_target); nothing to do."
fi
