#!/usr/bin/env bash
# eidolons sync — install/update Eidolons to match eidolons.yaml
# ═══════════════════════════════════════════════════════════════════════════

set -euo pipefail
SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
. "$SELF_DIR/lib.sh"

NON_INTERACTIVE=false
DRY_RUN=false

usage() {
  cat <<EOF
eidolons sync — install/update Eidolons to match eidolons.yaml

Usage: eidolons sync [OPTIONS]

Options:
  --non-interactive   Fail on prompts
  --dry-run           Show what would be done
  -h, --help          Show this help

Behavior:
  - Reads eidolons.yaml
  - For each member: fetches Eidolon repo, runs its install.sh with appropriate --hosts
  - Aggregates install.manifest.json from each member into eidolons.lock
  - Idempotent: safe to run repeatedly
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --non-interactive) NON_INTERACTIVE=true; shift ;;
    --dry-run)         DRY_RUN=true; shift ;;
    -h|--help)         usage; exit 0 ;;
    *)                 echo "Unknown option: $1" >&2; exit 2 ;;
  esac
done

manifest_exists || die "No eidolons.yaml found. Run 'eidolons init' first."

MANIFEST_JSON="$(yaml_to_json "$PROJECT_MANIFEST")"
HOSTS_CSV="$(echo "$MANIFEST_JSON" | jq -r '.hosts.wire | join(",")')"
MEMBERS_JSON="$(echo "$MANIFEST_JSON" | jq -c '.members[]')"

say "Syncing project to $PROJECT_MANIFEST"
info "Hosts: $HOSTS_CSV"

# ─── Lock file assembly ──────────────────────────────────────────────────
LOCK_TMP="$(mktemp)"
cat > "$LOCK_TMP" <<EOF
# eidolons.lock — auto-generated by 'eidolons sync'. Commit to VCS.
generated_at: "$(date -u +%FT%TZ)"
eidolons_cli_version: "${EIDOLONS_VERSION:-1.0.0}"
nexus_commit: "$(git -C "$NEXUS" rev-parse HEAD 2>/dev/null || echo unknown)"
members:
EOF

# ─── Per-member install ──────────────────────────────────────────────────
while read -r member; do
  name="$(echo "$member" | jq -r '.name')"
  version_spec="$(echo "$member" | jq -r '.version')"
  # Strip constraint prefix (^, ~, =) for cache key — proper resolution is a future task.
  version="${version_spec#^}"
  version="${version#~}"
  version="${version#=}"

  entry="$(roster_get "$name")"
  target="./.eidolons/$name"

  say "Installing $name@$version → $target"

  if [[ "$DRY_RUN" == "true" ]]; then
    info "  [dry-run] would fetch and install $name"
    continue
  fi

  clone_dir="$(fetch_eidolon "$name" "$version")"

  # EIIS sanity check (warn only; per-Eidolon install.sh is still the source of truth)
  eiis_check "$clone_dir" "$name" || true

  # Delegate to the Eidolon's own install.sh (EIIS §3 contract).
  if [[ ! -x "$clone_dir/install.sh" ]]; then
    warn "$name has no executable install.sh — EIIS v1.0 contract violated. Skipping."
    continue
  fi

  (
    cd "$(pwd)"  # ensure we stay in the consumer project
    bash "$clone_dir/install.sh" \
      --target "$target" \
      --hosts "$HOSTS_CSV" \
      ${NON_INTERACTIVE:+--non-interactive} \
      --force
  ) || { warn "$name install failed — continuing"; continue; }

  # ─── claude-code safety net ────────────────────────────────────────────
  # If the host wiring asked for claude-code but the per-Eidolon installer
  # didn't produce .claude/agents/<name>.md, write a minimal dispatch stub so
  # the agent is at least callable. Never overwrite an existing file.
  if [[ ",$HOSTS_CSV," == *",claude-code,"* ]] && [[ ! -f ".claude/agents/$name.md" ]]; then
    mkdir -p .claude/agents
    display="$(echo "$entry" | jq -r '.display_name // .name')"
    summary="$(echo "$entry" | jq -r '.methodology.summary // ""')"
    cat > ".claude/agents/$name.md" <<STUB
---
name: $name
description: $display — $summary
---

See ./.eidolons/$name/agent.md for the full methodology.
STUB
    info "  wrote .claude/agents/$name.md (nexus safety net)"
  fi

  # Pull the manifest emitted by the per-Eidolon install.sh
  if [[ -f "$target/install.manifest.json" ]]; then
    ver="$(jq -r '.version' "$target/install.manifest.json" 2>/dev/null || echo "$version")"
    commit="$(git -C "$clone_dir" rev-parse HEAD)"
    cat >> "$LOCK_TMP" <<LOCK
  - name: $name
    version: "$ver"
    resolved: "github:$(echo "$entry" | jq -r '.source.repo')@$commit"
    target: "$target"
    hosts_wired: $(jq -c '.hosts_wired' "$target/install.manifest.json")
LOCK
  else
    warn "$name did not produce install.manifest.json (not strictly EIIS-conformant)"
    cat >> "$LOCK_TMP" <<LOCK
  - name: $name
    version: "$version"
    resolved: "github:$(echo "$entry" | jq -r '.source.repo')"
    target: "$target"
    manifest_missing: true
LOCK
  fi

  ok "$name installed"
done <<< "$MEMBERS_JSON"

# ─── Write the lock ──────────────────────────────────────────────────────
mv "$LOCK_TMP" "$PROJECT_LOCK"
ok "Wrote $PROJECT_LOCK"

# ─── Final guidance ──────────────────────────────────────────────────────
echo ""
ok "Sync complete."
echo ""
cat <<EOF
Next steps:
  ${BOLD}eidolons doctor${RESET}              verify host wiring
  ${BOLD}eidolons list${RESET}                show installed members
  ${BOLD}cat $PROJECT_LOCK${RESET}            review resolved versions

Commit both eidolons.yaml and eidolons.lock to VCS.
EOF
